[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = default.csv
lib_deps =
    bblanchon/ArduinoJson@^6.21.0
    tzapu/WiFiManager@^2.0.17
build_flags =
    -DENABLE_OTA
    -DENABLE_WIFI_MANAGER
