[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = default.csv
lib_deps =
    bblanchon/ArduinoJson@6.18.5
    knolleary/PubSubClient@2.8
    links2004/WebSockets@2.4.1
build_flags =
    -DENABLE_OTA
    -DENABLE_WIFI_MANAGER
    -std=gnu++17

[env:native]
platform = native
build_flags =
    -std=gnu++17
    -DUNIT_TEST
    -Itest
    -Isrc
lib_deps =
    bblanchon/ArduinoJson@6.18.5
build_src_filter =
    +<test/Arduino.cpp>
    +<test/stubs.cpp>
    +<test/test_impls.cpp>
    +<test/test_pet_statemachine.cpp>
    +<test/test_spiffs_migration.cpp>
    +<test/test_achievements.cpp>
    +<test/test_lineage.cpp>
    +<test/test_stats.cpp>
    +<test/test_accessibility.cpp>
    +<test/test_backup.cpp>
    +<test/test_hal.cpp>
    +<test/test_provisioning.cpp>
    +<test/test_power.cpp>
    +<test/test_ota_delta.cpp>
    +<test/HAL_Native.cpp>
    +<test/OTA_Delta_Native.cpp>
    +<test/test_spriteloader.cpp>
    +<src/*>
test_filter = test_*
